name: Compilar APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Compilar con Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Guardar el APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartExpiry-apk
          path: ${{ steps.buildozer.outputs.filename }}
